### ISSUE TITLE
initial page load tracked twice

### ISSUE THREAD

**Issue by bitsagarob** [EmmanuelRoux/ngx-matomo#16]
initial page load is tracked twice. It seems trackAppInitialLoad, which is default false, is not working properly.

These all don't fix the issue:
Explicitly setting trackAppInitialLoad to false 
Tracking without NgxMatomoRouterModule
Tracking with NgxMatomoRouterModule
Tracking with NgxMatomoRouterModule and using a custom MATOMO_PAGE_TITLE_PROVIDER

**Comment by EmmanuelRoux** [comment]
Hi @segersrobbert 
Can you please show your code or provide a repro with an example?

**Comment by bitsagarob** [comment]
Cause turned out to be custom business logic
