### ISSUE TITLE
feat: enable javascript error tracking

### ISSUE THREAD

**Issue by santoshyadavdev** [EmmanuelRoux/ngx-matomo#37]
Matomo enables javascript error tracking

link below:

https://matomo.org/faq/how-to/how-do-i-enable-basic-javascript-error-tracking-and-reporting-in-matomo-browser-console-error-messages/

we need to add

_paq.push(['enableJSErrorTracking']);

let me know I am happy to contribute if this is accepted.

**Comment by EmmanuelRoux** [comment]
Hi @santoshyadavdev 
Of course you can provide a PR!
Thank you

**Comment by EmmanuelRoux** [comment]
Hi @santoshyadavdev 

Just in case you would like to provide a PR, I think there are two main points to deal with:
- The first is to add new method to `MatomoTracker` api
- The second (optional but appreciated!) is to provide a way to let user configure this behavior with a new configuration option

**Comment by EmmanuelRoux** [comment]
Hi @santoshyadavdev, 
Just to have an idea on planning, do you think you will be able to propose a PR (even partial) for this issue?
Thank you!
