### ISSUE TITLE
matomo.php is always appended to trackerUrl (branch 1.x)

### ISSUE THREAD

**Issue by traycold** [EmmanuelRoux/ngx-matomo#38]
The same issue (#24) has been solved on `main` branch, but is still present on branch `1.x`,

**Comment by EmmanuelRoux** [comment]
Hi @traycold, do you think you can provide a PR please?

You may cherry-pick bd93470e478e4e90d15ded5f7c15e981de481cd8

**Comment by traycold** [comment]
created PR ~~#39~~ #41 (I just verified compilation and tests are ok, but did not test real code in my app)
