### ISSUE TITLE
Missing mtmPreviewMode and mtmSetDebugFlag

### ISSUE THREAD

**Issue by Yberion** [EmmanuelRoux/ngx-matomo#43]
Hello,

When using the scripts provided by Matomo (`Matomo` and `Matomo Tag Manager`) we're able to get a Preview/Debug on a console when providing following query params : `https://website.com/?mtmPreviewMode=ContainerID&mtmSetDebugFlag=1`.

I tested to use those query params with this package but I'm not getting any result (no console), is it somehow not implemented in your lib or maybe I'm doing something wrong ?

I'm on Angular 13, last version of `ngx-matomo`, we have **S**erver **S**ide **R**endering but it shouldn't be enabled for the client (only robots) on our `Dev` platform.

Do you have any idea on how to display the preview/debug console using your lib ?

Thanks for your help.

**Comment by EmmanuelRoux** [comment]
Hello @Yberion,

It should theoretically be working as-is, since the lib is including Matomo JS client just like the manual tracking code.

Can you please provide a repro for further investigation?

Thanks!

**Comment by ValentinGot** [comment]
Hi @EmmanuelRoux,

I'm working with @Yberion.

Here is a reproduction of the debug console not working: https://angular-ivy-asprzg.stackblitz.io/?mtmPreviewMode=u3VEyzl4&mtmSetDebugFlag=1

You can access the code here: https://stackblitz.com/edit/angular-ivy-asprzg

As you can see, when trying to enable the debug console, nothing is happening.

Maybe we did something wrong in Matomo, but we are able to see the console when adding the scripts manually to the head.

**Comment by EmmanuelRoux** [comment]
Hi @ValentinGot 
Can you please also provide the script which is working when you include it manually ?

**Comment by EmmanuelRoux** [comment]
Hi @ValentinGot 
Can you please also provide the script which is working when you include it manually ?

Btw, I see your are not including the Tag Manager script in your configuration: you should add the `scriptUrl` property.
[See README here](https://github.com/EmmanuelRoux/ngx-matomo#scripts-with-pre-defined-embedded-tracker-configuration-tag-manager-variable)
Something like this:

```ts
NgxMatomoTrackerModule.forRoot({
  […]
  scriptUrl: 'http://yourserver/js/container_xxxxx.js'
}),
```

**Comment by ValentinGot** [comment]
Sure, i've created 2 javascripts files.

matomo.js
```js
var _mtm = window._mtm = window._mtm || [];
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.async=true; g.src='https://cdn.matomo.cloud/brittanyferries.matomo.cloud/container_658XUzVV.js'; s.parentNode.insertBefore(g,s);
```

tracking.js
```js
var _paq = window._paq = window._paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
  var u="https://brittanyferries.matomo.cloud/";
  _paq.push(['setTrackerUrl', u+'matomo.php']);
  _paq.push(['setSiteId', '1']);
  var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
  g.async=true; g.src='//cdn.matomo.cloud/brittanyferries.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
})();
```

And i've added them in the index.html file:
```html
<html>
  <head>
    <script src="https://URL/tracking.js"></script>
    <script src="https://URL/matomo.js" async defer></script>
  </head>
</html>
```

So, i should also add `scriptUrl: 'https://cdn.matomo.cloud/brittanyferries.matomo.cloud/container_658XUzVV.js'` in the configuration

**Comment by EmmanuelRoux** [comment]
@ValentinGot @Yberion 

I'm actually able to see the console on the link you provided (https://angular-ivy-asprzg.stackblitz.io/?mtmPreviewMode=u3VEyzl4&mtmSetDebugFlag=1).

This is your configuration:
```ts
@NgModule({
  imports: [
    NgxMatomoTrackerModule.forRoot({
      trackerUrl: 'https://xxxxxxxxxx.matomo.cloud/',
      siteId: '3',
      scriptUrl:
        'https://cdn.matomo.cloud/xxxxxxxxxx.matomo.cloud/container_xxxxxxx.js',
    }),
    NgxMatomoRouterModule,
    [...]
})
export class AppModule {}
```

![image](https://user-images.githubusercontent.com/1926413/169344865-d0b7424d-8c83-4dee-b80f-b4d15c0c8616.png)

**Comment by ValentinGot** [comment]
Hi @EmmanuelRoux,

Yep I managed to make it work yesterday afternoon with the **scriptUrl**. Thanks for the help :)
