### ISSUE TITLE
Angular 14 Update

### ISSUE THREAD

**Issue by jahusa02** [EmmanuelRoux/ngx-matomo#47]
Any Date when this project will get the update to Angular 14?

Thanks in advance

**Comment by EmmanuelRoux** [comment]
Hi @jahusa02, it's on the road and will be released very very soon

(In the meantime, you can force install of v2.4.2, since it's actually compatible with Angular 14)

**Comment by jahusa02** [comment]
Thanks!!!

**Comment by erwindemoel** [comment]
Awesome, thanks!
