### ISSUE TITLE
Calls to setCustomDimension() are working on init but not on event (Angular App)

### ISSUE THREAD

**Issue by R0mpo** [EmmanuelRoux/ngx-matomo#52]
Hello,

We have been noticing that call to setCustomDimension() method in order to set or update Matomo Custom Dimension are no longer working when they are linked to user's actions.

Our case : Once the application loaded, we set 2 different dimesions to our company's Matomo : 
 - user profile 
 - customerName (both are business infos, stored as string)

Once the user clic on a given element of the app, we were sending a 3rd Custom Dimension : "isActive". And while it worked for a while, it seams to have stop working since last week. If sending this even on the app load like the other 2, no issues happens and the dimension is set. If waiting for any user event, it doesn't.

Have you ever heard or anything similar happening within an Angular app ?
Is there any logs or reproduction details that could help for troubleshooting this ?

Looking forward hearing from you !

ps : I'm fluent in French if that can help explaining better the issue

**Comment by R0mpo** [comment]
PS : we realised this morning that if we force the sending of a "classic' event just after using setCustomDimension, then the custom dimension is well sent.

For now we will force sending a 'mock' event instantly after setting custom dimension

**Comment by EmmanuelRoux** [comment]
Hi @R0mpo, 

Note that custom dimensions are set for the _next request_, which is being sent using tracking methods such as `trackPageView` or `trackEvent`.

You can refer to matomo documentation for details: https://matomo.org/guide/reporting-tools/custom-dimensions/ and https://developer.matomo.org/api-reference/tracking-javascript

If you still have an issue, please provide a repro (Stackblitz...) so I can observe the described behavior.

**Comment by R0mpo** [comment]
Thank you for the precisions :)
