### ISSUE TITLE
Customizing script tag not working

### ISSUE THREAD

**Issue by abdunnahid** [EmmanuelRoux/ngx-matomo#56]
Application Version: Angular 13
@ngx-matomo/router: "^2.2.1"
@ngx-matomo/tracker: "^2.3.0"

**TypeError: Cannot read properties of undefined (reading 'createElement')**

I wanted to add "integrity" attribute on script tag for matomo.js. I tried using the way suggested in the [doc](https://github.com/EmmanuelRoux/ngx-matomo#advanced-use-cases)

The following is the code:
`
import { NgxMatomoTrackerModule } from '@ngx-matomo/tracker';
import { NgxMatomoRouterModule } from '@ngx-matomo/router';

const getMatomoScript = (scriptUrl: string, document: Document) => {
    console.log("🚀 ~ file: app.module.ts ~ line 33 ~ getMatomoScript ~ scriptUrl", scriptUrl)
    console.log("🚀 ~ file: app.module.ts ~ line 31 ~ getMatomoScript ~ document", document)

    const script = document.createElement('script');
    script.type = 'text/javascript';
    script.async = !0;
    script.src = scriptUrl;
    script.id = 'matomo-script';
    script.integrity = 'sha256-O2UvOjz2SgGApRDh4pNxKwPxgjt7BRYgz8861kVcBLQ=';
    script.crossOrigin = 'anonymous';

    return script;
}

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        HttpClientModule,
        AppRoutingModule,
        CommonModule,
        ...
        NgxMatomoTrackerModule.forRoot(
            {
                trackerUrl: environment.matomoConfig.appUrl,
                siteId: environment.matomoConfig.siteId
            },
            getMatomoScript
        ),
        NgxMatomoRouterModule,
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }
`
This throwing the error below:
![image](https://user-images.githubusercontent.com/16201576/180924869-3c7ad12c-1f85-4388-be40-b8976a81052f.png)

Anything I am doing wrong?

**Comment by EmmanuelRoux** [comment]
Hi @abdunnahid thank you for reporting this issue, a fix will be release very soon

**Comment by EmmanuelRoux** [comment]
@abdunnahid Fixed in versions 2.6.0 (for Angular 13) and 3.2.0 (for Angular 14)

**Comment by abdunnahid** [comment]
Yes it is fixed.
Thanks @EmmanuelRoux
