### ISSUE TITLE
Uncaught TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_5__.__param) is not a function

### ISSUE THREAD

**Issue by RolfVeinoeSorensen** [EmmanuelRoux/ngx-matomo#58]
When adding ngx-matomo to my angular 14 solution I am unable to load my site because of the error below:

NgxMatomoRouterModule is the culprit, the NgxMatomoTrackerModule is loading fine

Uncaught TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_5__.__param) is not a function
    at 54392 (ngx-matomo-router.mjs:87:12)

minified by webpack:
DefaultPageUrlProvider = __decorate([
    __param(0, Optional()),
    __param(0, Inject(INTERNAL_ROUTER_CONFIGURATION)),
    __param(1, Optional()),
    __param(1, Inject(APP_BASE_HREF))
], DefaultPageUrlProvider);

Current code:
export class DefaultPageUrlProvider implements PageUrlProvider {
  constructor(
    @Optional()
    @Inject(INTERNAL_ROUTER_CONFIGURATION)
    private readonly config: InternalRouterConfiguration,
    @Optional() @Inject(APP_BASE_HREF) private readonly baseHref: string | null,
    private readonly platformLocation: PlatformLocation
  ) {}

**Comment by RolfVeinoeSorensen** [comment]
tsconfig
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": false, //TODO check when swagger-codegen fixes encoder.ts override properties
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "module": "es2020",
    // "esModuleInterop": true, 
    "lib": [
      "es2020",
      "es2021",
      "dom"
    ],


package.json
    "@angular/animations": "^14.2.8",
    "@angular/cdk": "^14.2.1",
    "@angular/common": "^14.2.8",
    "@angular/compiler": "^14.2.8",
    "@angular/core": "^14.2.8",
    "@angular/forms": "^14.2.8",
    "@angular/platform-browser": "^14.2.8",
    "@angular/platform-browser-dynamic": "^14.2.8",
    "@angular/router": "^14.2.8",
    "@ngx-matomo/router": "^3.2.0",
    "@ngx-matomo/tracker": "^3.2.0",    
    "rxjs": "~7.4.0",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.4"

devdep: "typescript": "~4.7.4",

**Comment by EmmanuelRoux** [comment]
Hi @RolfVeinoeSorensen, could you please provide some reproductible code? (Stackblitz, GitHub repo...)

**Comment by EmmanuelRoux** [comment]
Hi @RolfVeinoeSorensen, is your problem solved?

**Comment by EmmanuelRoux** [comment]
Closed as not reproducible
