### ISSUE TITLE
Disable automatic send event

### ISSUE THREAD

**Issue by matissel** [EmmanuelRoux/ngx-matomo#64]
Hey,

I'd like to know how can we disable some events that are automatically sent to matomo. For example, I have an `input` with a "click" event that will redirect to a result page. I want to record result count and query term manually by using the `MatomoTracker` service. It works, however I have another event "search" that is recorded by default since we have a change of page with query params (the actual term searched in the bar). 

My custom event (with category 'click', action 'rechercherTermes', name 'Hello' and value 15 corresponding to result count) : 
![image](https://github.com/EmmanuelRoux/ngx-matomo/assets/1536264/656c1625-ad1f-410a-9d22-116435cf7f5a)
The associated code : 
![image](https://github.com/EmmanuelRoux/ngx-matomo/assets/1536264/8d665a1e-825d-4fb9-979d-745fd126c527)

Another one created by default, that I don't want (it's a duplicate and doesn't have the result count)
![image](https://github.com/EmmanuelRoux/ngx-matomo/assets/1536264/970712fe-6385-411c-bca2-22edc7a0aa2a)

The same issues occurs for some button that I have, that also `navigate` using Angular Router and therefore creates duplicated entries that I don't need. 
Thanks for the good work :)

**Comment by EmmanuelRoux** [comment]
Hi @matissel 

Could you please share a repro (stackblitz or similar) ? Or at least your Matomo configuration ?

> Thanks for the good work :)

Thanks! 🙏🏻

**Comment by matissel** [comment]
Hey,
I don't have any configuration apart from following the installation without angular cli here :  https://github.com/EmmanuelRoux/ngx-matomo/blob/main/docs/installation-without-cli.md (add both package and siteId/url).
Then these events are automatically fired... I'll try to get a repro but I doubt it will have much in it.

EDIT : Ok so I think I got it. Adding the NgxMatomoRouterModule will track page views so since all my buttons somehow `navigate` to certains pages, then it records new events for these. A good idea for flexibility would be to be able to enable/disable some navigation events (for example, record /home events to check user access to the page but disable /contact if we don't want to track accesses to this page). Same thing would apply for 'goto' link event. I want to record these events myself but the lib is already saving a `link` type event to Matomo

**Comment by EmmanuelRoux** [comment]
If you enable automatic page view tracking by adding `NgxMatomoRouterModule`, all page view are tracked by default.

1. **You can ignore some url patterns using the `exclude` option of `NgxMatomoRouterModule`.**
2. Also, `enableLinkTracking` option of `NgxMatomoTrackerModule` is enabled by default and will track all click events on _links_. You can try to disable it and see if that matches your needs.

Example:
```ts
@NgModule({
  imports: [
    // ...
    NgxMatomoTrackerModule.forRoot({
      siteId: environment.matomoSiteId,
      trackerUrl: environment.matomoTrackerUrl,
      enableLinkTracking: false, // 2. You can also add this to disable automatic link tracking
    }),
    NgxMatomoRouterModule.forRoot({
      exclude: /contact$/, // <-- 1. Exclude urls ending with "contact" from automatic page view tracking
    }),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

You can find all configuration options [in documentation](https://github.com/EmmanuelRoux/ngx-matomo/blob/d6ed276af6416f57dcb76aff8b02ec41b5ed1452/README.md#configuration-reference).

**Comment by matissel** [comment]
Nice ! Ok thanks, did not see the exclude options ! 
Will close the issue then

**Comment by EmmanuelRoux** [comment]
Added to [FAQ in README](https://github.com/EmmanuelRoux/ngx-matomo#how-to-exclude-some-routes-from-tracking)
