### ISSUE TITLE
Cookieless setup

### ISSUE THREAD

**Issue by seehundnz** [EmmanuelRoux/ngx-matomo#65]
Hi,

thank you for the helpful module.
I was wondering if it was possible to use Matomo's cookieless tracking.
When setting it up with angular it works great in standard setup and tracks my angular app, but it sets cookies although in Matomo-settings I set it to cookieless tracking. On my website cookieless tracking works without any problems.
I already tried to set the parameter 'scriptUrl' to my matomo.js, but then the app keeps on returning errors in the javascript console and reloads by itself the whole time. When entering the URL in my browser I can see the JS-file.

Any ideas how to solve this?

Thank you for your help.

Kind regards,

Sebastian

**Comment by EmmanuelRoux** [comment]
Hi @seehundnz 

Could you please share a very simple minimal reproduction of the issue? 
(At least, your detailed configuration would be helpful to investigate)

**Comment by EmmanuelRoux** [comment]
Hi @seehundnz,

I'm trying to set-up a quick repro for your issue : https://github.com/EmmanuelRoux/ngx-matomo/tree/demo-issue-65

__But I'm not able reproduce it.__ I'm setting `requireConsent: MatomoConsentMode.COOKIE` in the configuration, and I can see that no cookie is set until I explicitly click the button to give consent (`tracker.setCookieConsentGiven()`). Can you please share a repro with your issue?

Also:
> I already tried to set the parameter 'scriptUrl' to my matomo.js, but then the app keeps on returning errors in the javascript console and reloads by itself the whole time. When entering the URL in my browser I can see the JS-file.

"_the app keeps on returning errors_" is not very helpful... what errors are you getting exactly?

Thank you!

**Comment by seehundnz** [comment]
Hey Emmanuel,

sorry that it takes so long for me to reply.

I played around for quite a while and for some reason it resolved itself (I guess I just forgot to clear my cache).

I set the scriptURL as descriptor in your tutorial and it now just works.

Thank you anyway for your help. Sorry for the trouble.


Kind regards,

Sebastian

**Comment by EmmanuelRoux** [comment]
Good news!
