### ISSUE TITLE
Logging on secondary siteId

### ISSUE THREAD

**Issue by PerKlitgaard** [EmmanuelRoux/ngx-matomo#66]
Im not sure if its the right place to ask for a feature, or if its allready possible. :-)
The Matomo site script has a feature to log on a secondary siteId.
But is this possible in ngx-matomo? or is it af feature that have been thought about.

**Comment by EmmanuelRoux** [comment]
Hi @PerKlitgaard 

It's possible. Instead of using a simple configuration like this:

```ts
    NgxMatomoTrackerModule.forRoot({
      siteId: 'MAIN_SITE_ID',
      trackerUrl: 'MAIN_TRACKER_URL',
    }),
```

You can define multiple trackers config:

```ts
NgxMatomoTrackerModule.forRoot({
      trackers: [
        {
          siteId: 'SITE_ID_FOR_TRACKER_1',
          trackerUrl: 'TRACKER_1_URL',
        },
        {
          siteId: 'SITE_ID_FOR_TRACKER_2',
          trackerUrl: 'TRACKER_2_URL',
        },
      ],
      // Following is OPTIONAL. Script is by default obtained from the first tracker in the list.
      // But if you want it from another tracker or another location, provide its url here:
      scriptUrl: '<path to matomo.js>',
    }),
```

**Comment by PerKlitgaard** [comment]
Hi Emmanuel
Thaks a lot
I will try that

And thank you for a good package

/Per

**Comment by EmmanuelRoux** [comment]
Thanks, I'll let you close this issue once everything is ok for you 😉
