### ISSUE TITLE
Question about enabling/disabling tracker

### ISSUE THREAD

**Issue by rgustavsson** [EmmanuelRoux/ngx-matomo#74]
Hello!

Many thanks for a great library!

The ngx-tracker works perfectly well in my standard Angular application.

I'm using Scully.io for prerendering pages and see that I have an issue with matomo triggering before the Angular application itself has booted up and initialized the tracker properly (replaced the static html generated by scully).

Scully uses the browser to prerender and in some component I've just got an if statement saying "if scullyIsRunning, return".
I'd like to do something similar with this tracker and I've seen that it's possible to disable the tracker in app.module

Is it possible to enable it run-time? :)

I have read through the readme to see if I could enable this tracker globally in some other way where I have access to the scully service.

Any thoughts?

**Comment by EmmanuelRoux** [comment]
Hi @rgustavsson 

I’m not sure I understand deeply the problem, it’s difficult without a repro.

I would suggest to take a look at deferred initialization ([explained in README](https://github.com/EmmanuelRoux/ngx-matomo#how-to-define-configuration-asynchronously-http-fetch)). You can call `matomoInitializer.initializeTracker` at any time when your app is ready, nothing will be tracked before.

**Comment by rgustavsson** [comment]
This is perfect @EmmanuelRoux
I kind of missed the APP_INITIALIZER possibilites. Already had one so I justed hooked it up in there.
Many thanks!
