### ISSUE TITLE
Angular 17 Jest ReferenceError: Cannot access 'NgxMatomoRouterModule' before initialization

### ISSUE THREAD

**Issue by BrunelaManaj** [EmmanuelRoux/ngx-matomo#79]
After updating to Angular 17 and ngx-matomo-client 6.0.0 there are problems with the unit tests of the components/service, where Matomo Directives or MatomoTracker is being used. NgxMatomoRouterModule is not being used in the app, the matomo configuration is being done through the standalone function provideMatomo() and withRouter(). 
The problem occurs only after updating to the version 6.0.0 of matomo. In the version 5.0.4 there are no problems. 
Do you have any ideas, how we can use solve this problem?

**Comment by EmmanuelRoux** [comment]
Hi @BrunelaManaj, thanks for reporting this bug

I've published a test version: could you please try using version `6.0.1-fix-79.1` of `ngx-matomo-client`?

If that does not solve the problem, could you provide a repro so I can investigate further?

**Comment by BrunelaManaj** [comment]
Thanks a lot for your reply. I tested the version 6.0.1-fix-79.1 and there are no unit tests problems anymore.

**Comment by EmmanuelRoux** [comment]
Thanks! 

Version 6.0.1 (including this fix) will be released today

**Comment by BrunelaManaj** [comment]
Perfect, thanks a lot!

**Comment by matt-senseye** [comment]
Thanks for the fix. v6.0.1 fixed our Jest issues too 👍
