### ISSUE TITLE
Importing MatomoRouterModule results in Error retrieving getBaseHrefFromDOM

### ISSUE THREAD

**Issue by Viserius** [EmmanuelRoux/ngx-matomo#82]
Dear @EmmanuelRoux,

Adding `MatomoModule` to the module imports has been working for us so far in our Angular 17 application.
Since we now want to do some magic on setting a custom URL before sending results to the server, we tried adding the `MatomoRouterModule` to the imports as well.
Even before we add any custom configuration such as an interceptor, adding the `MatomoRouterModule` to our imports causes the following error to take place on a page load:

```
ERROR TypeError: Cannot read properties of null (reading 'endsWith')
    at trimTrailingSlash (ngx-matomo-client-router.mjs:178:16)
    at DefaultPageUrlProvider.getBaseHrefWithoutTrailingSlash (ngx-matomo-client-router.mjs:193:16)
    at DefaultPageUrlProvider.getCurrentPageUrl (ngx-matomo-client-router.mjs:188:20)
    at MatomoRouter.presetPageTitleAndUrl (ngx-matomo-client-router.mjs:271:14)
    at ngx-matomo-client-router.mjs:238:37
    at source.subscribe.isComplete (switchMap.js:14:23)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at subscribe.innerComplete (mergeInternals.js:25:28)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
```

Following the stacktrace reveals that the `trimTrailingSlash`-function is called with a null value through the line:
`trimTrailingSlash(this.baseHref ?? this.platformLocation.getBaseHrefFromDOM());`
Therefore, it seems that in our situation, getBaseHrefFromDOM returns null as well. After looking at [the documentation of PlatformLocation](https://angular.io/api/common/PlatformLocation), it states: 'This class should not be used directly by an application developer. Instead, use [Location](https://angular.io/api/common/Location).'.

Although I am unsure why `getBaseHrefFromDOM()` returns null, perhaps this is a side-effect of using a class that should not be called by a developer. Do you see a way to resolve this, by perhaps retrieving the value in a different way?

**Comment by EmmanuelRoux** [comment]
Hi @Viserius 

Thanks for reporting this bug 

You're right, [`LocationStrategy#getBaseHref`](https://angular.io/api/common/LocationStrategy#getBaseHref) should probably used instead.

(But in fact, `LocationSatrategy` is delegating to `platformLocation.getBaseHrefFromDO`... so I wonder why this bug appears. Could you provide a repro ?)

Feel free to open a PR to implement your suggested change, I will merge it soon !

**Comment by Viserius** [comment]
Although my PR does not solve the issue, using a HashLocationStrategy as opposed to the default PathLocationStrategy might be the problem.

**Comment by Viserius** [comment]
In our case, the null value might be caused by the fact that we do not specify a certain <base href="" /> tag in our HTML, causing the value to be null, meaning nonexistent. I will propose a bugfix.

**Comment by EmmanuelRoux** [comment]
Ok, the problem seems to come from a bad typing in Angular source code. See [here (L120-124)](https://github.com/angular/angular/blob/7b4d275f494a64c38b61cea7045ba8b6e8447b78/packages/common/src/location/platform_location.ts#L120C1-L124C1) and [here (L71-74)](https://github.com/angular/angular/blob/7b4d275f494a64c38b61cea7045ba8b6e8447b78/packages/platform-browser/src/browser/browser_adapter.ts#L71-L74)

```ts
  override getBaseHrefFromDOM(): string {
    return getDOM().getBaseHref(this._doc)!; // <-- This can actually be null !
  }
```
```ts
  override getBaseHref(doc: Document): string|null {
    const href = getBaseElementHref();
    return href == null ? null : relativePath(href);
  }
```

I will provide a workaround in addition to your PR, thanks for identifying this problem!

**Comment by Viserius** [comment]
@EmmanuelRoux Thank you for the unbelievably fast response times and thinking with me. Looking forward to using a new version. Any idea when you're able to make a release with this fix?

**Comment by EmmanuelRoux** [comment]
@Viserius I've added some comments to your PR to suggest something, please take a look
