### ISSUE TITLE
`MatomoTestingTracker` is missing the `Injectable` decorator and causing warnings

### ISSUE THREAD

**Issue by viceice** [EmmanuelRoux/ngx-matomo#85]
I get this warning when using the `provideMatomoTesting` provider helper:

```
DEPRECATED: DI is instantiating a token "MatomoTestingTracker" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in a future version of Angular. Please add @Injectable() to the "MatomoTestingTracker" class.
```

**Comment by EmmanuelRoux** [comment]
Hi @viceice 

you’re right, it’s a known "bug" (it should however work properly). 

Feel free to open a PR, it should be ok to just add `@Injectable()` to [this class](https://github.com/EmmanuelRoux/ngx-matomo-client/blob/main/projects/ngx-matomo-client/testing/matomo-testing-tracker.ts)

**Comment by viceice** [comment]
see linked PR 🙃
