### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by swurzinger** [EmmanuelRoux/ngx-matomo#90]
Version 6.x of ngx-matomo-client depends on angular 17.x and isn't compatible with 18.x. Please add support for the current Angular version.

At least the versions need to be bumped/widened in package.json. Maybe there are some other incompatibilies with Angular 18, but probably not.

Thanks!

**Comment by EmmanuelRoux** [comment]
Hi @swurzinger, indeed I will work on it very soon.
Don’t hesitate to suggest a PR if you have some time!
